[versions]
adventure = "4.17.0"

[libraries]
# Platforms
platform-paper = { module = "io.papermc.paper:paper-api", version = "1.20.4-R0.1-SNAPSHOT" }
platform-sponge = { module = "org.spongepowered:spongeapi", version = "10.0.0" }

adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventure-text-serializer-plain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventure" }
dazzleconf = { module = "space.arim.dazzleconf:dazzleconf-ext-snakeyaml", version = "1.3.0-M2" }
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.9" }
snakeyaml = { module = "org.yaml:snakeyaml", version = "2.2" }

# Plugins
plugin-miniplaceholders = { module = "io.github.miniplaceholders:miniplaceholders-api", version = "2.2.3" }
plugin-luckperms = { module = "net.luckperms:api", version = "5.4" }

[plugins]
pluginYml = { id = "net.minecrell.plugin-yml.bukkit", version = "0.6.0" }
sponge = { id = "org.spongepowered.gradle.plugin", version = "2.0.2" }